[project]
name = "texgenRedvin"
version = "0.1.0"
description = "Study package"
authors = [{ name = "Redvin", email = "pakman12344321@mail.ru" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["texgen"]
requires-python = ">=3.12"
dependencies = []

[project.urls]
Homepage = "https://github.com/Redvin-dt/PythonAdvancedHW"
